In [1]:
import pandas as pd
import numpy as np

In [2]:
m=pd.read_csv("tmdb_5000_movies.csv")
c=pd.read_csv("tmdb_5000_credits.csv")
movies=pd.merge(m,c,on="title")

In [3]:
movies = movies[['movie_id', 'title', 'overview', 'genres',
                 'keywords','cast', 'crew']]


In [4]:
movies.isnull().sum()
movies.dropna(inplace=True)
movies.duplicated().sum()


0

In [5]:
movies.iloc[0].genres 

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [6]:
import ast
ast.literal_eval

<function ast.literal_eval(node_or_string)>

In [7]:

def convert(obj):
    L=[]
    for i in obj:
        L.append(i["name"])
    return L
        


In [8]:
L=convert([{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {
        "id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}])
L


['Action', 'Adventure', 'Fantasy', 'Science Fiction']

In [9]:

def convert(obj):
    L=[]
    for i in ast.literal_eval(obj):
        L.append(i["name"])
    return L
        


In [10]:
convert(movies.iloc[0].genres)


['Action', 'Adventure', 'Fantasy', 'Science Fiction']

In [11]:
movies["genres"].apply(convert)

0       [Action, Adventure, Fantasy, Science Fiction]
1                        [Adventure, Fantasy, Action]
2                          [Action, Adventure, Crime]
3                    [Action, Crime, Drama, Thriller]
4                [Action, Adventure, Science Fiction]
                            ...                      
4804                        [Action, Crime, Thriller]
4805                                [Comedy, Romance]
4806               [Comedy, Drama, Romance, TV Movie]
4807                                               []
4808                                    [Documentary]
Name: genres, Length: 4806, dtype: object

In [12]:
movies["genres"]=movies["genres"].apply(convert)

In [13]:
movies["keywords"]=movies["keywords"].apply(convert)

In [14]:

def convert(obj):
    L = []
    counter=8
    for i in ast.literal_eval(obj):
        if counter !=3:
            L.append(i["name"])
            counter+=1
        else:
            break
    return L


In [15]:
movies['cast'].apply(convert)


0       [Sam Worthington, Zoe Saldana, Sigourney Weave...
1       [Johnny Depp, Orlando Bloom, Keira Knightley, ...
2       [Daniel Craig, Christoph Waltz, Léa Seydoux, R...
3       [Christian Bale, Michael Caine, Gary Oldman, A...
4       [Taylor Kitsch, Lynn Collins, Samantha Morton,...
                              ...                        
4804    [Carlos Gallardo, Jaime de Hoyos, Peter Marqua...
4805    [Edward Burns, Kerry Bishé, Marsha Dietlein, C...
4806    [Eric Mabius, Kristin Booth, Crystal Lowe, Geo...
4807    [Daniel Henney, Eliza Coupe, Bill Paxton, Alan...
4808    [Drew Barrymore, Brian Herzlinger, Corey Feldm...
Name: cast, Length: 4806, dtype: object

In [16]:
movies['cast']=movies['cast'].apply(convert)

In [17]:
movies['crew'][0]

'[{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "539c47ecc3a36810e3001f87", "department": "Art", "gender": 2, "id": 496, "job": "Production Design", "name": "Rick Carter"}, {"credit_id": "54491c89c3a3680fb4001cf7", "department": "Sound", "gender": 0, "id": 900, "job": "Sound Designer", "name": "Christopher Boyes"}, {"credit_id": "54491cb70e0a267480001bd0", "department": "Sound", "gender": 0, "id": 900, "job": "Supervising Sound Editor", "name": "Christopher Boyes"}, {"credit_id": "539c4a4cc3a36810c9002101", "department": "Production", "gender": 1, "id": 1262, "job": "Casting", "name": "Mali Finn"}, {"credit_id": "5544ee3b925141499f0008fc", "department": "Sound", "gender": 2, "id": 1729, "job": "Original Music Composer", "name": "James Horner"}, {"credit_id": "52fe48009251416c750ac9c3", "department": "Directing", "gender": 2, "id": 2710, "job": "Director", "name": "James Cameron"},

In [18]:
def fetch_director(obj):
    L=[]
    for i in ast.literal_eval(obj):
        if i['job']=='Director':
            L.append(i['name'])
            break
    return L

In [19]:
movies['crew'].apply(fetch_director)

0           [James Cameron]
1          [Gore Verbinski]
2              [Sam Mendes]
3       [Christopher Nolan]
4          [Andrew Stanton]
               ...         
4804     [Robert Rodriguez]
4805         [Edward Burns]
4806          [Scott Smith]
4807          [Daniel Hsia]
4808     [Brian Herzlinger]
Name: crew, Length: 4806, dtype: object

In [20]:
movies['crew']=movies['crew'].apply(fetch_director)

In [21]:
movies['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [22]:
movies['overview'].apply(lambda x:x.split())

0       [In, the, 22nd, century,, a, paraplegic, Marin...
1       [Captain, Barbossa,, long, believed, to, be, d...
2       [A, cryptic, message, from, Bond’s, past, send...
3       [Following, the, death, of, District, Attorney...
4       [John, Carter, is, a, war-weary,, former, mili...
                              ...                        
4804    [El, Mariachi, just, wants, to, play, his, gui...
4805    [A, newlywed, couple's, honeymoon, is, upended...
4806    ["Signed,, Sealed,, Delivered", introduces, a,...
4807    [When, ambitious, New, York, attorney, Sam, is...
4808    [Ever, since, the, second, grade, when, he, fi...
Name: overview, Length: 4806, dtype: object

In [23]:
movies['overview']=movies['overview'].apply(lambda x:x.split())

In [24]:
movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])

0       [Action, Adventure, Fantasy, ScienceFiction]
1                       [Adventure, Fantasy, Action]
2                         [Action, Adventure, Crime]
3                   [Action, Crime, Drama, Thriller]
4                [Action, Adventure, ScienceFiction]
                            ...                     
4804                       [Action, Crime, Thriller]
4805                               [Comedy, Romance]
4806               [Comedy, Drama, Romance, TVMovie]
4807                                              []
4808                                   [Documentary]
Name: genres, Length: 4806, dtype: object

In [25]:
movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])
movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])

0           [JamesCameron]
1          [GoreVerbinski]
2              [SamMendes]
3       [ChristopherNolan]
4          [AndrewStanton]
               ...        
4804     [RobertRodriguez]
4805         [EdwardBurns]
4806          [ScottSmith]
4807          [DanielHsia]
4808     [BrianHerzlinger]
Name: crew, Length: 4806, dtype: object

In [26]:
movies['tags']=movies['overview']+movies['genres']+movies['keywords']+movies['cast']+movies['crew']

In [27]:
new_df=movies[['movie_id','title','tags']]

In [28]:
new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

C:\Users\163544\AppData\Local\Temp\ipykernel_6952\487797088.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))


In [29]:
new_df['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy Science Fiction culture clash future space war space colony society space travel futuristic romance space alien tribe alien planet cgi marine soldier battle love affair anti war power relations mind and soul 3d Sam Worthington Zoe Saldana Sigourney Weaver Stephen Lang Michelle Rodriguez Giovanni Ribisi Joel David Moore CCH Pounder Wes Studi Laz Alonso Dileep Rao Matt Gerald Sean Anthony Moran Jason Whyte Scott Lawrence Kelly Kilgour James Patrick Pitt Sean Patrick Murphy Peter Dillon Kevin Dorman Kelson Henderson David Van Horn Jacob Tomuri Michael Blain-Rozgay Jon Curry Luke Hawker Woody Schultz Peter Mensah Sonia Yee Jahnel Curfman Ilram Choi Kyla Warren Lisa Roumain Debra Wilson Chris Mala Taylor Kibby Jodie Landau Julie Lamm Cullen B. Madden Joseph Brady Madden Frankie Torres Austin 

In [30]:
new_df['tags'].apply(lambda x:x.lower())

0       in the 22nd century, a paraplegic marine is di...
1       captain barbossa, long believed to be dead, ha...
2       a cryptic message from bond’s past sends him o...
3       following the death of district attorney harve...
4       john carter is a war-weary, former military ca...
                              ...                        
4804    el mariachi just wants to play his guitar and ...
4805    a newlywed couple's honeymoon is upended by th...
4806    "signed, sealed, delivered" introduces a dedic...
4807    when ambitious new york attorney sam is sent t...
4808    ever since the second grade when he first saw ...
Name: tags, Length: 4806, dtype: object

In [31]:
new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

C:\Users\163544\AppData\Local\Temp\ipykernel_6952\4224080999.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:x.lower())


In [32]:
new_df['tags'][1]

"captain barbossa, long believed to be dead, has come back to life and is headed to the edge of the earth with will turner and elizabeth swann. but nothing is quite as it seems. adventure fantasy action ocean drug abuse exotic island east india trading company love of one's life traitor shipwreck strong woman ship alliance calypso afterlife fighter pirate swashbuckler aftercreditsstinger johnny depp orlando bloom keira knightley stellan skarsgård chow yun-fat bill nighy geoffrey rush jack davenport kevin mcnally tom hollander naomie harris jonathan pryce keith richards lee arenberg mackenzie crook greg ellis david bailie martin klebba david schofield lauren maher vanessa branch angus barnett giles new reggie lee dominic scott kay takayo fischer david meunier ho-kwan tse andy beckwith peter donald badalamenti ii christopher s. capp keith richards hakeem kae-kazim ghassan massoud gore verbinski"

In [33]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000, stop_words='english')


In [34]:
cv.fit_transform(new_df['tags']).toarray()


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [35]:
cv.fit_transform(new_df['tags']).toarray().shape


(4806, 5000)

In [36]:
vectors = cv.fit_transform(new_df['tags']).toarray()


In [37]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [38]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [39]:
pip install nltk

Note: you may need to restart the kernel to use updated packages.


In [40]:
import nltk
nltk.download('punkt')


[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\163544\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [41]:
from nltk.stem.porter import PorterStemmer


In [42]:
import nltk
from nltk.stem import PorterStemmer

# Initialize the Porter Stemmer
stemmer = PorterStemmer()

# Stem a word
word = "jumping"
stemmed_word = stemmer.stem(word)
print(stemmed_word)  # Output: "jump"

# You need to make sure you have NLTK installed:
# Install NLTK if you haven't already
# pip install nltk


jump


In [43]:
ps=PorterStemmer()

In [44]:
def stem(text):
    y = []
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)


In [45]:
new_df['tags'].apply(stem)

0       in the 22nd century, a parapleg marin is dispa...
1       captain barbossa, long believ to be dead, ha c...
2       a cryptic messag from bond’ past send him on a...
3       follow the death of district attorney harvey d...
4       john carter is a war-weary, former militari ca...
                              ...                        
4804    el mariachi just want to play hi guitar and ca...
4805    a newlyw couple' honeymoon is upend by the arr...
4806    "signed, sealed, delivered" introduc a dedic q...
4807    when ambiti new york attorney sam is sent to s...
4808    ever sinc the second grade when he first saw h...
Name: tags, Length: 4806, dtype: object

In [46]:
new_df['tags']=new_df['tags'].apply(stem)

C:\Users\163544\AppData\Local\Temp\ipykernel_6952\3514595201.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(stem)


In [47]:
new_df['tags'][1300]

'a pair of age box rival are coax out of retir to fight one final bout -- 30 year after their last match. comedi father son relationship sport rivalri elderli elderli man robert de niro sylvest stallon alan arkin jon bernthal kevin hart kim basing ll cool j judd lormand nicol andrew han soto griff furst don lake camden gray carri lazar john l. armijo todd truley rowan joseph peter segal'

In [48]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000, stop_words='english')


In [49]:
pip install xarray


Note: you may need to restart the kernel to use updated packages.


In [50]:
vectors=cv.fit_transform(new_df['tags']).toarray()

In [51]:
from sklearn.feature_extraction.text import CountVectorizer

# Sample text data
corpus = ["This is the first document.",
          "This document is the second document.", "And this is the third one."]

# Create a CountVectorizer
vectorizer = CountVectorizer()

# Fit and transform the text data
X = vectorizer.fit_transform(corpus)

# Get the feature names
feature_names = vectorizer.get_feature_names_out()

# Print the feature names
print(feature_names)


['and' 'document' 'first' 'is' 'one' 'second' 'the' 'third' 'this']


In [52]:
from sklearn.metrics.pairwise import cosine_similarity


In [53]:
similarity = cosine_similarity(vectors)
cosine_similarity(vectors).shape


(4806, 4806)

In [54]:
similarity


array([[1.        , 0.10881351, 0.07927124, ..., 0.03464015, 0.01900543,
        0.01536191],
       [0.10881351, 1.        , 0.07938842, ..., 0.0375823 , 0.01374643,
        0.02222222],
       [0.07927124, 0.07938842, 1.        , ..., 0.0238688 , 0.05238277,
        0.        ],
       ...,
       [0.03464015, 0.0375823 , 0.0238688 , ..., 1.        , 0.03719683,
        0.04509876],
       [0.01900543, 0.01374643, 0.05238277, ..., 0.03719683, 1.        ,
        0.06598289],
       [0.01536191, 0.02222222, 0.        , ..., 0.04509876, 0.06598289,
        1.        ]])

In [55]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])

[(0, 1.0000000000000002),
 (47, 0.3017318023494271),
 (2409, 0.30149839166852865),
 (149, 0.281451220037393),
 (65, 0.26532607018881077),
 (1216, 0.2623611139382941),
 (1537, 0.25966362889046096),
 (1920, 0.253825649699079),
 (158, 0.2490384025487984),
 (507, 0.24790171554530396),
 (1321, 0.2466984290363284),
 (218, 0.2401888567236763),
 (110, 0.2389433395128927),
 (322, 0.23624607804052644),
 (278, 0.23481812262849727),
 (1607, 0.2337367852823266),
 (2204, 0.23348563864528488),
 (3162, 0.23268303344655972),
 (305, 0.23211322981563567),
 (4048, 0.2313248221920752),
 (838, 0.2290086764844313),
 (505, 0.22893627067137456),
 (4336, 0.22890761423482825),
 (270, 0.22811268756929876),
 (2239, 0.22806517893865344),
 (1082, 0.2277196711990031),
 (3675, 0.22595384385027567),
 (72, 0.22422253919312196),
 (3, 0.22212349222678546),
 (4, 0.22177267137135853),
 (598, 0.21998299271308816),
 (582, 0.21773457205625582),
 (1383, 0.21694136514992582),
 (25, 0.21567839629547517),
 (52, 0.2150490055616034)

In [56]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])[1:6]

[(47, 0.3017318023494271),
 (2409, 0.30149839166852865),
 (149, 0.281451220037393),
 (65, 0.26532607018881077),
 (1216, 0.2623611139382941)]

In [57]:
def recommend(movie):
    movie_index=new_df[new_df['title']==movie].index[0]
    distance=similarity[movie_index]
    movies_list=sorted(list(enumerate(distance)),reverse=True,key=lambda x:x[1])[1:6]
    
    for i in movies_list:
        print(new_df.iloc[i[0]].title)
    


In [58]:
recommend('Avatar')

Star Trek Into Darkness
Aliens
Armageddon
The Dark Knight
Aliens vs Predator: Requiem


In [59]:
import pickle

In [60]:
pickle.dump(new_df,open('movies.pkl','wb'))
pickle.dump(new_df.to_dict(),open('movies_dict.pkl','wb'))

In [61]:
new_df[new_df['title']=='Avatar']

movie_id   title                                               tags
0     19995  Avatar  in the 22nd century, a parapleg marin is dispa...

In [62]:
new_df[new_df['title']=='Avatar'].index[0]

0

In [63]:
new_df[new_df['title']=='Batman Begins'].index[0]

119

In [64]:
recommend('Batman Begins')

The Dark Knight Rises
The Dark Knight
Superman
The Fifth Element
The Departed


In [65]:
pickle.dump(similarity,open('similarity.pkl','wb'))